### ISSUE TITLE
Are there other triggers for this?

### ISSUE THREAD

**Issue by wcphart** [Firebottle/Mixer-Support-Alert#1]
I see several streams trigger their support overlay (assuming its this one, as they look the same I think) when specific users chat for the 1st time. Though it does not show the command in chat.

Scorpbot can send a message on 1st chat, but that shows the command in chat. Thought maybe somehow this is able to trigger on 1st chat by name, as well as a chat command (!so for example)

**Comment by itsjesski** [comment]
The one you see was actually based off of this one, but they're not the same. This is a super bare bones project that doesn't offer any advanced functionality like you're wanting. I believe the one you're looking for is called pixelshout.

**Comment by wcphart** [comment]
Thanks, I tried that, it... sometimes acted up. Happy Friday.

**Comment by itsjesski** [comment]
Yeah, I'd work on these other projects more but Firebot takes up pretty much all of my dev time nowadays. So, a lot of these older projects are a bit dated at this point. I created most of them shortly after I joined Beam.

Happy friday!
