### ISSUE TITLE
Issue: User Roles Not Working

### ISSUE THREAD

**Issue by kopacko** [Firebottle/Mixer-Support-Alert#2]
Regardless of what channel I target for this script, the usernames all show as blue, instead of if the user is Pro or if they are a moderator in the channel, etc.

Any idea what is wrong and what do you need from me?

**Comment by itsjesski** [comment]
Can you try now? Thanks for the report!

**Comment by kopacko** [comment]
Thanks,
The other thing I noticed is that the user's group is not being identified.
If they are a Pro Member, Staff, Moderator, etc. This piece changes the
color of the user name on the display.

**Comment by itsjesski** [comment]
Yep, that's what should be fixed now. The color of the name will show different depending on their role.
