### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by DelboyDylan** [Firebottle/Mixer-Support-Alert#4]
I was just testing this out, and noticed a spelling mistake when it shows what someone was last streaming. "where" should be "were".

**Comment by ThePerry-2015** [comment]
Not sure why no one has mentioned or fixed that one earlier. Thank you for your report. :)
It won't be visible in the overlay yet as the change needs to be pushed to the website first, have to wait for the site admin to handle that part.

**Comment by ThePerry-2015** [comment]
Then it has been updated on the website and should be visible in the overlay.
